### ISSUE TITLE
Doesn't work with mesos 0.20

### ISSUE THREAD

**Issue by florianleibert** [nqn/angstrom#9]
jclouds@development-386-c48:~$ go get github.com/nqn/angstrom/{angstrom,angstrom-executor}
# github.com/mesosphere/mesos-go/mesos

In file included from /usr/local/include/mesos/mesos.hpp:22:0,
                 from /usr/local/include/mesos/executor.hpp:26,
                 from src/github.com/mesosphere/mesos-go/mesos/executor_driver.cpp:5:
/usr/local/include/mesos/mesos.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
/usr/local/include/mesos/mesos.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
/usr/local/include/mesos/mesos.pb.h:14:2: error: #error your headers.
In file included from /usr/local/include/mesos/mesos.hpp:22:0,
                 from /usr/local/include/mesos/executor.hpp:26,
                 from src/github.com/mesosphere/mesos-go/mesos/executor_driver.cpp:5:
/usr/local/include/mesos/mesos.pb.h:26:55: fatal error: google/protobuf/generated_enum_reflection.h: No such file or directory
compilation terminated.
